# Generated by Django 4.0.3 on 2022-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterPoint', models.CharField(max_length=100)),
                ('meter', models.CharField(max_length=100)),
                ('reading', models.FileField(upload_to='data/uffs')),
            ],
        ),
    ]
